### PR TITLE
Updated CSV Preview

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
Made preview only first 4 values rather than complete csv file, added headers to table, shortened code.

screen shot 2017-12-18 at 2 59 56 pm

Issue #26 & #27

### CODE REVIEW

**Comment by SachinRammoorthy** [comment]
Can this PR be merged? Any changes required?

**Comment by divyanshkul** [comment]
@SachinRammoorthy I guess the current merge is pretty adequate considering the functionality of this project. I think the user should be able to to preview all the data, the minimum 4 values thing was just for the task I guess, also, to reduce the number of values being printed, you could have just edited the for loop which was running till the total length.

**Comment by garg-anuj** [comment]
@SachinRammoorthy can you please resolve conflicts of readme

**Comment by SachinRammoorthy** [comment]
@garg-anuj Have resolved conflicts.

**Pull request closed without merging**
