### PR TITLE
Added CSV Preview for Certifier

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
Added preview for generating certificates in bulk. Option to upload csv file or directly paste into text area. Can also edit csv file in text area before downloading certificate. Preview created in table (see screenshots).

GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5126300844949504/

Screenshots:
________

screen shot 2017-12-17 at 12 44 02 pm
screen shot 2017-12-17 at 12 44 18 pm
screen shot 2017-12-17 at 12 44 23 pm

### CODE REVIEW

**Comment by yashovardhanagrawal** [comment]
anyway I checked it on the server.. its working fine but why you have 2 input boxes? the second one is of no use, delete that

**Comment by SachinRammoorthy** [comment]
@yashovardhanagrawal Screenshots are already uploaded. Please see PR description/first comment...

**Comment by yashovardhanagrawal** [comment]
oh you edited it, sorry I missed it, will check it again in some other browser maybe

**Comment by yashovardhanagrawal** [comment]
submit the task for review again

**Comment by SachinRammoorthy** [comment]
@yashovardhanagrawal already done :)

**Comment by yashovardhanagrawal** [comment]
duplicate of #35

**Pull request closed without merging**
